### ISSUE TITLE
注册账号中验证邮箱时的验证链接错误

### ISSUE THREAD

**Issue by occulticplus** [NankaiACM/NKOJ-Back-End#15]
验证邮件中给出的验证链接如下
undefined/api/u/verify/766115f4607f78abb1d0193fc5219d37/990147
猜想是链接生成时某个变量缺少定义
mailTemplate和mail.js中显示{undefined}应为'${BASE_URL}'，且从/config/basic.js里面获取此变量。但是basic.js里面没有此变量的定义。猜想添加定义“BASE_URL='acm.nankai.edu.cn'”可以解决此问题。

**Comment by Alexhaoge** [comment]
邮件发送功能在lib/mail.js中，生成链接的BASE_URL来自`config/path`
https://github.com/NankaiACM/NKOJ-Back-End/blob/5d1a7f5ae16d427bcadab21d7773362f5b9559a3/lib/mail.js#L9
https://github.com/NankaiACM/NKOJ-Back-End/blob/5d1a7f5ae16d427bcadab21d7773362f5b9559a3/lib/mail.js#L38

这个path.js应该是秘密文件，样式参见`path_template.js`
https://github.com/NankaiACM/NKOJ-Back-End/blob/5d1a7f5ae16d427bcadab21d7773362f5b9559a3/init/path_template.js#L3 
事实上oj这里写的居然是localhost...

然后点击的那个link，是单独传参的，然后倒了一圈发现这个是用户注册接口从`config/basic`这里调用BASE_URL，但是这里并没有。。。

**Comment by Alexhaoge** [comment]
邮件发送功能在lib/mail.js中，生成链接的BASE_URL来自`config/path`
https://github.com/NankaiACM/NKOJ-Back-End/blob/5d1a7f5ae16d427bcadab21d7773362f5b9559a3/lib/mail.js#L9
https://github.com/NankaiACM/NKOJ-Back-End/blob/5d1a7f5ae16d427bcadab21d7773362f5b9559a3/lib/mail.js#L38

这个path.js应该是秘密文件，样式参见`path_template.js`
https://github.com/NankaiACM/NKOJ-Back-End/blob/5d1a7f5ae16d427bcadab21d7773362f5b9559a3/init/path_template.js#L3 
事实上oj这里写的居然是localhost...

然后点击的那个link，是单独传参的，然后倒了一圈发现这个是用户注册接口从`config/basic`这里调用BASE_URL，但是这里并没有。。。

**Comment by Alexhaoge** [comment]
fixed in commit [a30b35f](https://github.com/NankaiACM/NKOJ-Back-End/commit/a30b35f86f7c15e402993eb514d8e4127fb1f583)
